config/routes.rb
Rails.application.routes.draw do
  get 'movies/comingsoon', to: 'movies#comingsoon'
  get 'movies/hot', to: 'movies#hot'
  get 'movies/weekly', to: 'movies#weekly'

  post '/', to: 'movies#index'

  get '*path' => redirect('/')

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	include HTTParty
	serialize :genres,Array
	serialize :casts,Array
	serialize :directors,Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
require 'MovieApi.rb'

class MoviesController < ApplicationController
	def index
		@time = Time.current.to_s
		search_string = params[:search]
		if params[:search].present?
			if search_string.chars.count < search_string.bytes.count
				text_ascii = '\u'+search_string.ord.to_s(16)
				@searchmovies = ::MovieApi.get_movies("search?q=#{text_ascii}").movies	
			else
				@searchmovies = ::MovieApi.get_movies("search?q=#{search_string}").movies	
			end
		else
			@searchmovies = ::MovieApi.get_movies("coming_soon").movies
		end
	end

	def hot
		@hotmovies = ::MovieApi.get_movies("new_movies?apikey=0b2bdeda43b5688921839c8ecb20399b").movies	
	end

	def comingsoon
		@comingmovies = ::MovieApi.get_movies("coming_soon").movies
	end

	def weekly
		@weeklymovies = ::MovieApi.get_movies("weekly?apikey=0b2bdeda43b5688921839c8ecb20399b").movies
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movienight</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/comingsoon.html.erb
<p>COMING SOON</p>
<%= link_to 'Home', root_path %>
<%= link_to 'Hot Movies', movies_hot_path %>
<%= link_to 'Coming Soon', movies_comingsoon_path %>
<%= link_to 'Weekly Top Movies', movies_weekly_path %>
<table>
	<thead>
		<tr>
			<th>Image</th>
			<th>Title</th>
			<th>Original Title</th>
			<th>Rating</th>
			<th>Year</th>
		</tr>
	</thead>

	<tbody>
		<% @comingmovies.each do |movie| %>
			<tr>
				<td><%= image_tag movie['images']['small']%></td>
				<td><%= movie['title']%></td>
				<td><%= movie['original_title']%></td>
				<td><%= movie['rating']['average']%></td>
				<td><%= movie['year']%></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/movies/hot.html.erb
<p>HOT</p>
<%= link_to 'Home', root_path %>
<%= link_to 'Hot Movies', movies_hot_path %>
<%= link_to 'Coming Soon', movies_comingsoon_path %>
<%= link_to 'Weekly Top Movies', movies_weekly_path %>
<table>
	<thead>
		<tr>
			<th>Image</th>
			<th>Title</th>
			<th>Original Title</th>
			<th>Rating</th>
			<th>Duration</th>
			<th>Year</th>
		</tr>
	</thead>

	<tbody>
		<% @hotmovies.each do |movie| %>
			<tr>
				<td><%= image_tag movie['images']['small']%></td>
				<td><%= movie['title']%></td>
				<td><%= movie['original_title']%></td>
				<td><%= movie['rating']['average']%></td>
				<td><%= movie['durations'][0]%></td>
				<td><%= movie['year']%></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/movies/index.html.erb
<h1>
	Hello! @<%= @time%>
</h1>
<div>
	<%= link_to 'Hot Movies', movies_hot_path %>
	<%= link_to 'Coming Soon', movies_comingsoon_path %>
	<%= link_to 'Weekly Top Movies', movies_weekly_path %>
</div>

<div>
	<p>Search</p>
	<%= form_tag root_path do %>
	  <%= text_field_tag :search, params[:search] %>
	  <%= submit_tag 'Search', name: nil %>
	<% end %>
</div>

<table>
	<tbody>
		<% @searchmovies.each do |movie| %>
			<tr>
				<td><%= image_tag movie['images']['medium']%></td>
				<td><%= movie['title']%></td>
				<td><%= movie['original_title']%></td>
				<td><%= movie['rating']['average']%></td>
				<td><%= movie['year']%></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/movies/weekly.html.erb
<p>WEEKLY</p>
<%= link_to 'Home', root_path %>
<%= link_to 'Hot Movies', movies_hot_path %>
<%= link_to 'Coming Soon', movies_comingsoon_path %>
<%= link_to 'Weekly Top Movies', movies_weekly_path %>
<table>
	<thead>
		<tr>
			<th>Image</th>
			<th>Title</th>
			<th>Original Title</th>
			<th>Rating</th>
			<th>Duration</th>
			<th>Year</th>
		</tr>
	</thead>

	<tbody>
		<% @weeklymovies.each do |movie| %>
			<tr>
				<td><%= image_tag movie['subject']['images']['large']%></td>
				<td><%= movie['subject']['title']%></td>
				<td><%= movie['subject']['original_title']%></td>
				<td><%= movie['subject']['rating']['average']%></td>
				<td><%= movie['subject']['durations'][0]%></td>
				<td><%= movie['subject']['year']%></td>
			</tr>
		<% end %>
	</tbody>
</table>